Add right sign in/out time directly in attendances
ckaenzig/tiny-hamster pull request #9
Opened 2018-10-13 12:21 UTC by Tonow-c2c

Like that attendances are directly correct :wink: 
![image](https://user-images.githubusercontent.com/32262135/46905387-25b82500-cef3-11e8-8433-d7696f2a8811.png)

2018-10-13 15:22 UTC, Tonow requested changes

2018-10-13 15:22 UTC, Tonow commented on tinyham.py
>  day_total = sum([infos[0] for infos in activities.values()], datetime.timedelta())
This line is useless

2018-10-15 18:36 UTC, Tonow approved these changes

2020-08-19 09:04 UTC, Tonow-c2c commented
Seems nobody use this now :disappointed:

2020-08-19 09:04 UTC, closed without merging